version: "2"
services:
  
  python:
    container_name: python
    build: 
      context: .
      dockerfile: docker/app.Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    depends_on:
      - mysql
    
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    env_file: 
      - ./backend/.env
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local